# Holding registers written by PLC
HR_COMMAND_ID = 0
HR_CAMERA_ID = 1
HR_CASSETTE_TYPE = 2
HR_COMMAND = 3
HR_FLAGS = 4
HR_PLC_HEARTBEAT = 5

# Input-register-like result area exposed by the server
IR_RESULT_COMMAND_ID = 100
IR_STATE = 101
IR_RESULT_CODE = 102
IR_ERROR_CODE = 103
IR_PROCESSING_TIME_HI = 104
IR_PROCESSING_TIME_LO = 105
IR_SLOT_COUNT = 106
IR_CAMERA_STATUS = 107
IR_APP_HEARTBEAT = 108
IR_SLOT_MAP_START = 200

COMMAND_NONE = 0
COMMAND_INSPECT = 1
COMMAND_ACK = 2
COMMAND_RESET_ERROR = 3
